---
config:
  logLevel: 'debug'
  theme: 'neutral'
---

timeline
    title Chronologie du Musée de l'Air et de l'Espace
    section Fondation
      1918 : Création du Conservatoire de l’aéronautique
      1919 : Première exposition publique à Issy-les-Moulineaux
      1921 : Inauguration du musée à Chalais-Meudon
    section Expansion
      1936 : Transfert partiel à Paris, boulevard Victor
      1937 : Inauguration de l’aérogare du Bourget
      1940 : Bombardement et fermeture du musée
      1945 : Réouverture à Chalais-Meudon
    section Modernisation
      1951 : Fondation de l’AAMA
      1973 : Décision de transfert au Bourget
      1975 : Inauguration du premier hall au Bourget
      1981 : Fermeture du site de Chalais-Meudon
      1983 : Inauguration du hall de l’Espace
      1987 : Ouverture de la Grande Galerie
    section Nouveaux espaces
      1995 : Installation de la maquette Ariane 5
      1996 : Construction du hangar pour Concorde 001
      2013 : Rénovation de la salle des Huit Colonnes
      2017 : Inauguration de la réserve Jean-Paul Béchat
      2019 : Centenaire et Grande Galerie rénovée
      2020 : Ouverture de la tour de contrôle historique
      2022 : Travaux de la réserve grands aéronefs
      2023 : Ouverture de la médiathèque-ludothèque 